### ISSUE TITLE
Venn Diagram not working anymore

### ISSUE THREAD

**Issue by pontikos** [phenopolis/phenopolis#26]
https://uclex.cs.ucl.ac.uk/individual/WebsterURMD_Sample_GV4344

Error:
```
Uncaught SyntaxError: Unexpected token <
WebsterURMD_Sample_GV4344:65771 Uncaught TypeError: venn.VennDiagram is not a function
    at WebsterURMD_Sample_GV4344:65771
```

**Comment by IsmailM** [comment]
The individual template has the following line (see [here](https://github.com/pontikos/phenopolis/blob/46ad83573840f5c54c9bb4352e7b124eff213fea/templates/individual.html#L332)):

```
 <script type="text/javascript" src="/static/js/node_modules/venn.js/venn.js"></script>
```

This file does not exist, and so returns a 404 page. This 404 page (being HTML) starts with the `<` which is why it gives that error message...

Fix is to upload venn.js into `static/js` and update the link (and the same line in the [transcript page](https://github.com/pontikos/phenopolis/blob/46ad83573840f5c54c9bb4352e7b124eff213fea/templates/transcript.html#L278))

Just to confirm, is this the library in question? https://github.com/benfred/venn.js/

**Comment by pontikos** [comment]
Thanks that fixed it!
